namespace CUplayKit.UbiServices
{
    public class Enums
    {
        public Dictionary<string, List<string>> CurrencyToCountry = new()
        {
            { "ARS", new() { "br"} },
            { "AUD", new() {"anz"} },
            { "BRL", new() {"br"} },
            { "CAD", new() {"ca"} },
            { "CLP", new() {"br"} },
            { "CNY", new() {"cn"} },
            { "COP", new() {"br"} },
            { "CRC", new() {"br"} },
            { "CZK", new() {"eu"} },
            { "DKK", new() {"eu"} },
            { "EUR", new() {"eu", "ie", "fr", "de", "es", "at", "it", "nl"} },
            { "GBP", new() {"uk"} },
            { "HKD", new() {"sea"} },
            { "HUF", new() {"eu"} },
            { "IDR", new() {"sea"} },
            { "JPY", new() {"jp"} },
            { "KRW", new() {"kr"} },
            { "MXN", new() {"br"} },
            { "MYR", new() {"sea"} },
            { "NOK", new() {"ie"} },
            { "NZD", new() {"anz"} },
            { "PEN", new() {"br"} },
            { "PHP", new() {"sea"} },
            { "PLN", new() {"eu"} },
            { "RUB", new() {"ru"} },
            { "SEK", new() {"eu"} },
            { "SGD", new() {"sea"} },
            { "THB", new() {"sea"} },
            { "TRY", new() {"tr"} },
            { "TWD", new() {"sea"} },
            { "USD", new() {"br", "ie", "sea", "us"} },
            { "UYU", new() {"br"} }
        };

        public enum CountryCode
        {
            anz,
            at,
            br,
            ca,
            cn,
            de,
            es,
            eu,
            fr,
            ie,
            it,
            jp,
            kr,
            nl,
            ru,
            sea,
            tr,
            uk,
            us
        }

        public enum LocaleCode
        {
            ar_AE,
            zh_CN,
            zh_TW,
            zh_HK,
            cs_CZ,
            da_DK,
            nl_NL,
            en_GB,
            en_CA,
            en_US,
            fi_FI,
            fr_FR,
            fr_CA,
            de_DE,
            hu_HU,
            it_IT,
            ja_JP,
            ko_KR,
            nb_NO,
            pl_PL,
            pt_PT,
            pt_BR,
            ru_RU,
            es_ES,
            es_MX,
            sv_SE,
            th_TH,
            tr_TR,
            uk_UA
        }

        public enum StoreVersion
        {
            v17_1,
            v17_2,
            v17_3,
            v17_4,
            v17_6,
            v17_7,
            v17_8,
            v18_1,
            v18_2,
            v18_3,
            v18_6,
            v18_7,
            v18_8,
            v19_1,
            v19_3,
            v19_5,
            v19_8,
            v19_10,
            v20_2,
            v20_3,
            v20_4,
            v20_8,
            v20_9,
            v20_10,
            v21_2,
            v21_3,
            v21_6,
            v21_8,
            v21_9,
            v21_10,
            v22_4,
            v22_6,
            v22_8,
            v22_10
        }

        public enum StoreCurrency
        {
            ARS,
            AUD,
            BRL,
            CAD,
            CLP,
            CNY,
            COP,
            CRC,
            CZK,
            DKK,
            EUR,
            GBP,
            HKD,
            HUF,
            IDR,
            JPY,
            KRW,
            MXN,
            MYR,
            NOK,
            NZD,
            PEN,
            PHP,
            PLN,
            RUB,
            SEK,
            SGD,
            THB,
            TRY,
            TWD,
            USD,
            UYU
        }
    }
}
