# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish Server/Server.sln -c:Release -o:Server

    - name : Upload artifacts
      uses: actions/upload-artifact@v4.3.5
      with:
        # Artifact name
        name: Server
        # A file, directory or wildcard pattern that describes what to upload
        path: Server/*
