# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build upc_r2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build x86
      run: dotnet publish Client/upc_r2/upc_r2.csproj -r win-x86 -c:Release -p:Platform=x86 -o:upc_r2

    - name: Build x64
      run: dotnet publish Client/upc_r2/upc_r2.csproj -r win-x64 -c:Release -p:Platform=x64 -o:upc_r2

    - name : Upload artifacts
      uses: actions/upload-artifact@v4.3.5
      with:
        # Artifact name
        name: upc_r2
        # A file, directory or wildcard pattern that describes what to upload
        path: upc_r2/*
